import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import './globals.css';

import { dehydrate, HydrationBoundary, QueryClient } from '@tanstack/react-query';

import { Footer } from '@/components/footer';
import { Navbar } from '@/components/navbar';
import { AuthProvider } from '@/features/auth/context.client';
import { fetchAuthenticatedUser } from '@/features/auth/user.server';

import Providers from './providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = new QueryClient();

  await queryClient.prefetchQuery({
    queryKey: ['auth'],
    queryFn: fetchAuthenticatedUser,
  });

  return (
    <html lang="fr">
      <body className={inter.className}>
        <Providers>
          <HydrationBoundary state={dehydrate(queryClient)}>
            <AuthProvider>
              <Navbar />
              <main>{children}</main>
              <Footer />
            </AuthProvider>
          </HydrationBoundary>
        </Providers>
      </body>
    </html>
  );
}
